server:
  port: 8001
  context-path: /
  session:
    timeout: -1


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/rabbitmq?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    # 使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  #设置开启热部署

  devtools:
    restart:
      enabled: true  #设置开启热部署

  http:
    multipart:
      max-file-size: 600Mb
      max-request-size: 600Mb
    encoding:
      charset: UTF-8

  #springboot整合rabbitmq基本配置
  rabbitmq:
    addresses: 192.168.56.101
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    ## 采用消息确认模式，保证消息100%投递
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

# 自定义属性
order:
  exchange: order-exchange  #交换器名称
  routingKey: order.abc    #队列路由key,由消费者的key【order.*】匹配对应
