package com.tiger.rabbitmq.dao;

import com.tiger.rabbitmq.entity.BrokerMessageLog;
import com.tiger.rabbitmq.entity.BrokerMessageLogExample;
import com.tiger.rabbitmq.mybatis.base.IBaseMapper;
import com.tiger.rabbitmq.mybatis.base.PageParameter;
import com.tiger.rabbitmq.mybatis.query.Query;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface BrokerMessageLogMapper extends IBaseMapper<BrokerMessageLog, BrokerMessageLogExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table broker_message_log
     *
     * @mbggenerated
     */
    int countByExample(BrokerMessageLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table broker_message_log
     *
     * @mbggenerated
     */
    int deleteByExample(BrokerMessageLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table broker_message_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table broker_message_log
     *
     * @mbggenerated
     */
    int insert(BrokerMessageLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table broker_message_log
     *
     * @mbggenerated
     */
    int insertSelective(BrokerMessageLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table broker_message_log
     *
     * @mbggenerated
     */
    List<BrokerMessageLog> selectByExample(BrokerMessageLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table broker_message_log
     *
     * @mbggenerated
     */
    BrokerMessageLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table broker_message_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BrokerMessageLog record, @Param("example") BrokerMessageLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table broker_message_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BrokerMessageLog record, @Param("example") BrokerMessageLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table broker_message_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BrokerMessageLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table broker_message_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BrokerMessageLog record);

    List<BrokerMessageLog> query(@Param("query") Query query, PageParameter pageParameter);
}